services:
  # Banco de dados MySQL
  mysql:
    image: mysql:8.0
    container_name: churches-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: churches_db
      MYSQL_USER: church_user
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - church-manager-network
    command: --default-authentication-plugin=mysql_native_password

  # Aplicação Spring Boot
  app:
    build:
      context: .
    container_name: churches-spring-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/churches_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: church_user
      SPRING_DATASOURCE_PASSWORD: 1234
      
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
    depends_on:
      - mysql
    networks:
      - church-manager-network
    ports:
      - "8082:8080"

networks:
  church-manager-network:
    external: true

volumes:
  mysql_data:
    driver: local
